In [11]:
import mlflow
import pandas as pd
import numpy as np
import sklearn

In [2]:
ben = np.load('../data/trial_ben.npy')
mal = np.load('../data/trial_mal.npy')
print(ben,mal)

[[0. 0. 0. ... 0. 0. 0.]
 [1. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 1. 1. ... 0. 0. 0.]
 [1. 1. 1. ... 0. 0. 0.]
 [0. 1. 0. ... 0. 0. 0.]] [[0. 1. 0. ... 0. 0. 0.]
 [1. 1. 0. ... 0. 0. 0.]
 [1. 0. 0. ... 0. 0. 0.]
 ...
 [0. 1. 0. ... 0. 0. 0.]
 [1. 0. 0. ... 1. 0. 0.]
 [0. 1. 0. ... 0. 0. 0.]]


In [3]:

id = 'runs:/984c6217d8cb4da6bd79ff089cca7355'

black_box = mlflow.pyfunc.load_model(f"{id}/BB")
gen = mlflow.pyfunc.load_model(f"{id}/generator")
print(black_box, gen)


/app/.venv/lib/python3.10/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm


mlflow.pyfunc.loaded_model:
  artifact_path: BB
  flavor: mlflow.sklearn
  run_id: 984c6217d8cb4da6bd79ff089cca7355
 mlflow.pyfunc.loaded_model:
  artifact_path: generator
  flavor: mlflow.pytorch
  run_id: 984c6217d8cb4da6bd79ff089cca7355



In [4]:
entry = mal[0]
initial_pred = black_box.predict(pd.DataFrame(mal))
obf = gen.predict(pd.DataFrame(mal))

Is training: False


In [ ]:
mod_pred = black_box.predict(obf)
sklearn.metrics.f1_score(np.ones(mod_pred.shape), mod_pred, average='binary') # F1 score

0.8945454545454545

: 

0.8945454545454545